server:
  port: 8087
  servlet:
    context-path: /api

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL

  # Spring Data JPA confuguration
  jpa:
    hipernate:
      # To be updated in real production usage!
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org:
      springframework: ERROR