server:
  port: 8089
  servlet:
    context-path: /api

spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      platform: h2
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:test;MODE=PostgreSQL;

#  datasource:
#    platform: MYSQL
#    url: jdbc:mysql://mysql:3306/tsbacked
#      username: ${session-hiber.dbUser}
#      password: ${session-hiber.dbPassword}

  #   Spring Data JPA confuguration
  jpa:
    show-sql: true
    generate-ddl: true
    hipernate:
      # To be updated in real production usage!
      ddl-auto: create-drop

logging:
  level:
    org:
      springframework: ERROR